build_image:
  image: docker:git
  services:
  - docker:dind
  before_script:
  - git config --global http.sslVerify false
  script:
    - git submodule update --init
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/providentai/aragon .
    - docker push registry.gitlab.com/providentai/aragon:latest
  only:
    - master
